### PR TITLE
feature -> develop | Feature/added store vendor crud

### PR DESCRIPTION
**Pull request by bharatkumar-j001**
### List of all the tasks

Format of information to be provided

---

#### [Task #289 - VaahStore > Backend > Store > Vendor > Development](https://team.webreinvent.com/backend/collab/project/vaahcms/tasks/289)
**Time invested:** 18:28:34 format | **Billable**: 18:28:34 | **Non-Billable**: hh:mm

**Client's comment or requirement**

**Proof of your testing, video, or image link?**
https://img-v4.getdemo.dev/screenshot/chrome_1UEyjuQ7tZ.mp4

---

### Feature Merge Request Checklist

- [x] have you rebase your `feature` with `develop`?
- [ ] have run `npm run prod` after `rebase` with `develop` branch in all your `Modules` & `Themes`? Notes, you have to reactivate modules and themes to publish assets.
- [x] have you updated the `patch` (`x.x.<update-this>`) version `config.php` and `composer.json` of module & theme?
- [x] have you read all the `comments` & `notes` in `wireframe` and verified that you have taken care of that?
- [x] verify that the `UI` must match with `design` & `wireframe` if available?
- [x] have you applied `data-testid` tag to `links`, `forms` & all `form inputs` like `input`, `select`?
- [x] did you verify the latest commit of `develop` exists in your `feature` branch after rebase?
- [x] have you tested the `feature` as per the client requirement?
- [x] did you follow the proper naming conventions in your code?
- [x] have you commented on your code with proper explanation?

### CODE REVIEW

**Comment by themodernpk** [comment]
@bharatkumar-j001 `Approved By` column should be auto-filled with the current user when a new record is being created, but not in case update. If you didn't understand my statement please discuss.

**Comment by themodernpk** [comment]
@bharatkumar-j001 "approved" status must be green in color

**Comment by themodernpk** [comment]
@bharatkumar-j001 https://drive.google.com/file/d/1ekX2cOkY0MuLIRgeWVSqJSKUkv1LQmOH/view

**Comment by bharatkumar-j001** [comment]
@themodernpk  sir i had got all the point except the last point about **default**  (https://drive.google.com/file/d/1ekX2cOkY0MuLIRgeWVSqJSKUkv1LQmOH/view)

**Pull request merged**
